version: '3'

services:
  drupal:
    image: bitnami/drupal:latest
    ports:
      - '8080:8080'
    environment:
      - MARIADB_HOST=db
      - MARIADB_PORT_NUMBER=3306
      - DRUPAL_DATABASE_USER=YAM428
      - DRUPAL_DATABASE_PASSWORD='030121008'
      - DRUPAL_DATABASE_NAME=final

  db:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_USER=YAM428
      - MARIADB_PASSWORD='030121008'
      - MARIADB_DATABASE=final

  webserver:
    image: nginx
    ports:
      - '80:80'
    depends_on:
      - drupal

  certbot:
    image: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - webserver
