version: '3'

services:
  drupal:
    image: bitnami/drupal:latest
    ports:
      - '8080:8080'
    environment:
      - MARIADB_HOST=db
      - MARIADB_PORT_NUMBER=3306
      - DRUPAL_DATABASE_USER=YAM428
      - DRUPAL_DATABASE_PASSWORD='030121008'
      - DRUPAL_DATABASE_NAME=final

  db:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_USER=YAM428
      - MARIADB_PASSWORD='030121008'
      - MARIADB_DATABASE=final

  webserver:
    image: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - drupal
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
  certbot:
    image: certbot/certbot
    restart: always
    depends_on:
      - nginx
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --yusuf.erkamyed@gmail.com--agree-tos --no-eff-email -d  yusufdrymz.live

