version: '3'

services:
  drupal:
    image: bitnami/drupal:latest
    ports:
      - '8080:8080'
    environment:
      - MARIADB_HOST=db
      - MARIADB_PORT_NUMBER=3306
      - DRUPAL_DATABASE_USER=${USER}
      - DRUPAL_DATABASE_PASSWORD=${PASSWORD}
      - DRUPAL_DATABASE_NAME=${DATABASE}

  db:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_USER=${USER}
      - MARIADB_PASSWORD=${PASSWORD}
      - MARIADB_DATABASE=${DATABASE}

  webserver:
    image: nginx
    ports:
      - '80:80'
    depends_on:
      - drupal

  certbot:
    image: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - webserver
